import type {
  CodeEditorProps,
  KeymapConfig,
  KernelStatus,
  NotebookCellType,
  ThemeVariables,
  VuepyterLocale,
} from './types'

export const DEFAULT_NBFORMAT = 4
export const DEFAULT_NBFORMAT_MINOR = 5

export const DEFAULT_PYODIDE_URL = 'https://cdn.jsdelivr.net/pyodide/v0.27.3/full/pyodide.mjs'

export const DEFAULT_CELL_TYPES: NotebookCellType[] = ['code', 'markdown', 'raw']

export const DEFAULT_KERNEL_STATUS: KernelStatus = 'loading'

export const DEFAULT_KEYMAP: KeymapConfig = {
  runCellAndAdvance: 'Shift+Enter',
  runCellAndStay: 'Mod+Enter',
  runCellAndInsertBelow: 'Alt+Enter',
  moveCellUp: 'ArrowUp',
  moveCellDown: 'ArrowDown',
  moveCellUpSecondary: 'K',
  moveCellDownSecondary: 'J',
  extendSelectionUp: 'Shift+ArrowUp',
  extendSelectionDown: 'Shift+ArrowDown',
  extendSelectionTop: 'Shift+Home',
  extendSelectionBottom: 'Shift+End',
  moveCellUpPosition: 'Ctrl+Shift+ArrowUp',
  moveCellDownPosition: 'Ctrl+Shift+ArrowDown',
  addCellBelow: 'B',
  addCellAbove: 'A',
  insertHeadingAbove: 'Shift+A',
  insertHeadingBelow: 'Shift+B',
  deleteCell: 'D D',
  undoCellAction: 'Z',
  redoCellAction: 'Shift+Z',
  copyCell: 'C',
  cutCell: 'X',
  pasteCellBelow: 'V',
  pasteCellAbove: 'Shift+V',
  mergeCells: 'Shift+M',
  mergeCellAbove: 'Ctrl+Backspace',
  mergeCellBelow: 'Ctrl+Shift+M',
  changeCellToCode: 'Y',
  changeCellToMarkdown: 'M',
  changeCellToRaw: 'R',
  changeCellToHeading1: '1',
  changeCellToHeading2: '2',
  changeCellToHeading3: '3',
  changeCellToHeading4: '4',
  changeCellToHeading5: '5',
  changeCellToHeading6: '6',
  enterEditMode: 'Enter',
  enterCommandMode: 'Escape',
  enterCommandModeSecondary: 'Ctrl+M',
  collapseHeading: 'ArrowLeft',
  expandHeading: 'ArrowRight',
  collapseAllHeadings: 'Ctrl+Shift+ArrowLeft',
  expandAllHeadings: 'Ctrl+Shift+ArrowRight',
  selectAllCells: 'Ctrl+A',
  toggleLineNumbers: 'L',
  toggleAllLineNumbers: 'Shift+L',
  toggleOutput: 'O',
  toggleOutputScrolling: 'Shift+O',
  toggleRenderSideBySide: 'Shift+R',
  showShortcuts: 'H',
  interruptKernel: 'I I',
  restartKernel: '0 0',
  saveCommand: 'S',
  historyPrevious: 'Alt+ArrowUp',
  historyNext: 'Alt+ArrowDown',
  invokeCompleter: 'Tab',
  showTooltip: 'Shift+Tab',
  dismissTooltip: 'Escape',
  splitCellAtCursor: 'Mod+Shift+-',
  exitEditMode: 'Escape',
  save: 'Mod+S',
  runCellStay: 'Ctrl+Enter',
  moveCellAbove: 'K',
  moveCellBelow: 'J',
  toggleMarkdownEdit: 'Enter',
  toggleMarkdownCommand: 'Escape',
}

export const DEFAULT_LOCALE: VuepyterLocale = {
  addCodeCell: 'Add code cell',
  addMarkdownCell: 'Add markdown cell',
  deleteCell: 'Delete cell',
  runCell: 'Run cell',
  runAllCells: 'Run all cells',
  restartKernel: 'Restart kernel',
  interruptKernel: 'Interrupt',
  clearAllOutputs: 'Clear outputs',
  statusLoading: 'Loading',
  statusReady: 'Ready',
  statusBusy: 'Busy',
  statusError: 'Error',
  cellTypeCode: 'Code',
  cellTypeMarkdown: 'Markdown',
  cellTypeRaw: 'Raw',
}

export const DEFAULT_EDITOR_OPTIONS: Partial<CodeEditorProps> = {
  lineNumbers: true,
  lineWrapping: true,
  indentUnit: 4,
  tabSize: 4,
  extensions: [],
}

export const LIGHT_THEME: ThemeVariables = {
  '--vuepyter-bg': '#f8fafc',
  '--vuepyter-cell-bg': '#ffffff',
  '--vuepyter-cell-border': '#e2e8f0',
  '--vuepyter-cell-active-border': '#2563eb',
  '--vuepyter-cell-active-line-bg': '#f1f5f9',
  '--vuepyter-text': '#0f172a',
  '--vuepyter-text-secondary': '#475569',
  '--vuepyter-font-mono': 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  '--vuepyter-font-size': '14px',
  '--vuepyter-output-bg': '#f8fafc',
  '--vuepyter-error-color': '#dc2626',
  '--vuepyter-toolbar-bg': '#ffffff',
  '--vuepyter-button-bg': '#f1f5f9',
  '--vuepyter-button-hover-bg': '#e2e8f0',
  '--vuepyter-status-ready': '#16a34a',
  '--vuepyter-status-busy': '#d97706',
  '--vuepyter-status-error': '#dc2626',
  '--vuepyter-cursor-color': '#0f172a',
  '--vuepyter-selection-bg': '#c7d2fe',
  '--vuepyter-syntax-keyword': '#7c3aed',
  '--vuepyter-syntax-string': '#16a34a',
  '--vuepyter-syntax-number': '#2563eb',
  '--vuepyter-syntax-comment': '#6b7280',
  '--vuepyter-syntax-function': '#d97706',
  '--vuepyter-syntax-variable': '#0f172a',
  '--vuepyter-syntax-operator': '#e11d48',
  '--vuepyter-content-max-width': '1040px',
}

export const DARK_THEME: ThemeVariables = {
  '--vuepyter-bg': '#0f172a',
  '--vuepyter-cell-bg': '#111827',
  '--vuepyter-cell-border': '#334155',
  '--vuepyter-cell-active-border': '#60a5fa',
  '--vuepyter-cell-active-line-bg': '#1f2937',
  '--vuepyter-text': '#e5e7eb',
  '--vuepyter-text-secondary': '#94a3b8',
  '--vuepyter-font-mono': 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  '--vuepyter-font-size': '14px',
  '--vuepyter-output-bg': '#0b1220',
  '--vuepyter-error-color': '#f87171',
  '--vuepyter-toolbar-bg': '#111827',
  '--vuepyter-button-bg': '#1f2937',
  '--vuepyter-button-hover-bg': '#334155',
  '--vuepyter-status-ready': '#22c55e',
  '--vuepyter-status-busy': '#f59e0b',
  '--vuepyter-status-error': '#ef4444',
  '--vuepyter-cursor-color': '#e5e7eb',
  '--vuepyter-selection-bg': '#3730a3',
  '--vuepyter-syntax-keyword': '#a78bfa',
  '--vuepyter-syntax-string': '#4ade80',
  '--vuepyter-syntax-number': '#60a5fa',
  '--vuepyter-syntax-comment': '#94a3b8',
  '--vuepyter-syntax-function': '#fbbf24',
  '--vuepyter-syntax-variable': '#e5e7eb',
  '--vuepyter-syntax-operator': '#fb7185',
  '--vuepyter-content-max-width': '1040px',
}

export const THEME_PRESETS = {
  light: LIGHT_THEME,
  dark: DARK_THEME,
} as const

export const LIGHT_THEME_VARIABLES = LIGHT_THEME
export const DARK_THEME_VARIABLES = DARK_THEME
